config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :cadastros
  resources :turmas do
    resources :alunos
  end

  get 'home/index'
  root 'home#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.secretaria?
      can :manage, User, cargo: 'Professor'
    elsif user.admin?
      can :manage, User, :all
    end
  end
end

app/models/aluno.rb
class Aluno < ApplicationRecord
  belongs_to :turma

  validates_presence_of :nome

  validates_presence_of :matricula
  validates_uniqueness_of :matricula

  validates_presence_of :email
  validates_uniqueness_of :email
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/turma.rb
class Turma < ApplicationRecord
  has_many :alunos
  belongs_to :user, optional: true

  enum dias: [:Domingo, :Segunda, :Terça, :Quarta, :Quinta, :Sexta, :Sábado]

  validates_presence_of :nome
  validates_presence_of :inicio
  validates_presence_of :fim
  validates_presence_of :cargamin
  validates_presence_of :cargamax
  validates_presence_of :capacidade

  validate :horario_deve_ser_valido
  validate :usuario_deve_ser_professor

  scope :dia_nao_conflitante, -> (dia) { where.not(dias: dia) }
  scope :dia_conflitante, -> (dia, id) { where(dias: dia).where.not(id: id) }

  scope :horario_nao_conflitante, -> (inicio, fim) do
    where.not(":inicio > inicio and :inicio < fim", inicio: inicio).where.not(":fim > inicio and :fim < fim", fim: fim)
  end

  scope :disponiveis, -> (inicio, fim, dia, id) do
    dia_nao_conflitante(dia).or(dia_conflitante(dia, id).horario_nao_conflitante(inicio, fim))
  end

  private
  def horario_deve_ser_valido
    if self.inicio >= self.fim
      errors.add(:horario_invalido, "horário de início não deve ser igual ou depois do horário de fim.")
    end
  end

  def usuario_deve_ser_professor
    unless user.nil?
      unless user.professor?
        errors.add(:cargo_invalido, "deve ter o cargo de professor")
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable :registerable,
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attr_accessor :login

  has_many :turmas

  validates_presence_of :nome
  validates_uniqueness_of :nome

  validates_presence_of :matricula
  validates_uniqueness_of :matricula

  scope :cargo, -> (cargo) {where(cargo: cargo)}

  scope :disponiveis, -> (turma) do
    left_outer_joins(:turmas).cargo("Professor").merge(Turma.disponiveis(turma.inicio, turma.fim, turma.dias, turma.id).or(where("turmas.id is NULL")))
  end

  def admin?
    self.cargo == "Admin"
  end

  def secretaria?
    self.cargo == "Secretaria"
  end

  def professor?
    self.cargo == "Professor"
  end

  def self.find_for_database_authentication warden_conditions
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions).where(["lower(nome) = :value OR lower(matricula) = :value", { value: login.strip.downcase } ]).first
  end
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController

  def edit
    @turma = Turma.find(params[:turma_id])
    @aluno = Aluno.find(params[:id])
  end

  def create
    @turma = Turma.find(params[:turma_id])
    @aluno = @turma.alunos.create(aluno_params)

    redirect_to turma_path(@turma), notice: "Aluno cadastrado com sucesso!"
  end

  def update
    @turma = Turma.find(params[:turma_id])
    @aluno = Aluno.find(params[:id])

    if @aluno.update(aluno_params)
      redirect_to turma_path(@aluno.turma), notice: "Aluno editado com sucesso."
    else
      render 'edit'
    end
  end

  def destroy
    @turma = Turma.find(params[:id])
    @aluno = @turma.alunos.find(params[:id])
    @aluno.destroy

    redirect_to turma_path(@turma)
  end

  private
  def aluno_params
    params.require(:aluno).permit(:nome, :matricula, :email)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nome, :matricula, :email, :cargo, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:login, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nome, :matricula, :email])
  end
end

app/controllers/cadastros_controller.rb
class CadastrosController < ApplicationController
  before_action :authorize_admin, only: :create

  def index
    @users = User.accessible_by(current_ability)
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, notice: "Usuário cadastrado com sucesso."
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(update_params)
      if @user.professor?
        redirect_to root_path, notice: "Dados alterados com sucesso!"
      else
        redirect_to cadastros_path, notice: "Dados alterados com sucesso."
      end
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    if @user.destroy
      redirect_to cadastros_path, notice: "Usuário removido."
    else
      render 'index', notice: "Não foi possível remover o usuário."
    end

  end

  private
  def authorize_admin
    return if current_user.admin? || current_user.secretaria?
    redirect_to root_path, alert: 'Apenas administradores.'
  end

  def user_params
    params.require(:user).permit(:nome, :matricula, :email, :cargo, :password, :password_confirmation)
  end

  def update_params
    params.require(:user).permit(:email)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/turmas_controller.rb
class TurmasController < ApplicationController

  def index
    @turmas = Turma.all
  end

  def show
    @turma = Turma.find(params[:id])
  end

  def new
    @turma = Turma.new
  end

  def edit
    @turma = Turma.find(params[:id])
  end

  def create
    @turma = Turma.new(turma_params)

    if @turma.save
      redirect_to turmas_path, notice: "Turma criada com sucesso!"
    else
      render 'new'
    end
  end

  def update
    @turma = Turma.find(params[:id])

    if @turma.update(turma_edit_params)
      redirect_to turmas_path
    else
      render 'edit'
    end
  end

  def destroy
    @turma = Turma.find(params[:id])

    if @turma.destroy
      redirect_to turmas_path, notice: "Turma removida com sucesso!"
    else
      render turmas_path, warn: "Não foi possível remover a turma!"
    end
  end

  private
  def turma_params
    params.require(:turma).permit(:nome, :dias, :inicio, :fim, :cargamin, :cargamax, :capacidade)
  end

  def turma_edit_params
    params.require(:turma).permit(:nome, :dias, :inicio, :fim, :cargamin, :cargamax, :capacidade, :user_id)
  end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    {:success => "alert-success", :error => "alert-danger", :alert => "alert-warning", :notice => "alert-info"}.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: "alert") do
        concat content_tag(:button, 'x', class: "close", data: { dismiss: "alert"})
        concat message
      end)
    end
    nil
  end
end

app/helpers/cadastros_helper.rb
module CadastrosHelper
  def gera_cargos(user)
    if user.admin?
      %w(Admin Secretaria)
    elsif user.secretaria?
      ["Professor"]
    else
      [""]
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/turmas_helper.rb
module TurmasHelper
  def vagas_restando(turma)
    pluralize(turma.capacidade - turma.alunos.count, 'vaga')
  end

  def prof_disponiveis(turma)
    options_from_collection_for_select(User.disponiveis(turma), :id, :nome, selected: turma.user)
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/alunos/edit.html.erb
<div class="container">
  <h2 class="text-center pb-2 mt-4 mb-2 border-bottom">Editar Aluno</h2>

  <% if @aluno.errors.any? %>
    <div id="error_explanation">
      <h5>
        <%= pluralize(@turma.errors.count, "erro") %> impediram esta turma de ser salva:
      </h5>
      <ul>
        <% @turma.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with model: [@turma, @aluno] do |f| %>
    <div class="container">


      <div class="form-group">
        <div class="field">
          <%= f.label :nome, "Nome" %><br>
          <%= f.text_field :nome, autofocus: true, class: "form-control", id: "inputNome" %>
        </div>
      </div>

      <div class="row">
        <div class="col">
          <div class="form-group">
            <div class="field">
              <%= f.label :matricula, "Matricula" %><br>
              <%= f.text_field :matricula, class: "form-control" %>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="form-group">
            <div class="field">
              <%= f.label :email, "Email" %><br>
              <%= f.text_field :email, class: "form-control" %>
            </div>
          </div>
        </div>
      </div>

      <div class="text-center">
        <%= f.submit 'Salvar Alterações', class: "btn btn-lg btn-outline-primary" %>
      </div>

    </div>
  <% end %>
</div>

app/views/cadastros/edit.html.erb
<div class="container">
  <h2 class="text-center pb-2 mt-4 mb-2 border-bottom">Editar cadastro</h2>
  <h5 class="text-center"><%= @user.nome %></h5>

  <%= form_with model: @user, url: cadastro_path(@user), method: :patch do |f| %>

    <div class="form-group">
      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email", :class => "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <div class="actions text-center">
        <%= f.submit "Update", :class => "btn btn-lg btn-outline-primary" %>
      </div>
    </div>

  <% end %>

  <%= link_to "Back", :back %>
</div>

app/views/cadastros/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <% if current_user.admin? %>
      <h1 class="display-5">Administração</h1>
      <p class="lead">Cadastro, edição e remoção de administradores e secretários.</p>
    <% elsif current_user.secretaria? %>
      <h1 class="display-5">Secretaria</h1>
      <p class="lead">Cadastro, edição e remoção de professores.</p>
    <% elsif current_user.professor? %>
      <h1 class="display-5">Professores</h1>
      <p class="lead">¯\_(ツ)_/¯</p>
    <% else %>
      <h1 class="display-5">Você não deveria estar aqui.</h1>
      <p class="lead">hmm.</p>
    <% end %>
  </div>
</div>
<div class="container">

  <table class="table table-bordered table-hover table-responsive-sm">
    <thead class="thead-dark">
      <tr>
        <th scope="col">User ID</th>
        <th scope="col">Nome</th>
        <th scope="col">Matrícula</th>
        <th scope="col">Email</th>
        <th scope="col">Cargo</th>
        <th colspan="2" scope="colgroup">Controles</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <th scope="row"><%= user.id %></th>
          <td><%= user.nome %></td>
          <td><%= user.matricula %></td>
          <td><%= user.email %></td>
          <td><%= user.cargo %></td>
          <td class="text-center"><%= link_to 'Editar', edit_cadastro_path(user), class: "btn btn-secondary btn-sm" %></td>
          <td class="text-center"><%= link_to 'Remover', cadastro_path(user), method: :delete, data: { confirm: "Tem certeza?" }, class: "btn btn-danger btn-sm" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to "Cadastrar novo usuário", new_cadastro_path, class: "btn btn-outline-primary btn-lg" %>

</div>

app/views/cadastros/new.html.erb
<div class="container">
  <h2 class="text-center pb-2 mt-4 mb-2 border-bottom">Cadastro de usuário</h2>

  <%= render "devise/shared/error_messages", resource: @user %>
  <div class="container">

    <%= form_with model: @user, url: cadastros_path, method: :post do |f| %>
      <div class="form-group">
        <div class="field">
          <%= f.label :nome, "Nome" %><br />
          <%= f.text_field :nome, autofocus:true, autocomplete: "nome", :class => "form-control" %>
        </div>
      </div>

      <div class="row">

        <div class="col-3">
          <div class="form-group">
            <div class="field">
              <%= f.label :matricula, "Matrícula" %><br />
              <%= f.text_field :matricula, autocomplete: "matricula", :class => "form-control" %>
            </div>
          </div>
        </div>

        <div class="col-6">
          <div class="form-group">
            <div class="field">
              <%= f.label :email, "E-mail" %><br />
              <%= f.email_field :email, autocomplete: "email", :class => "form-control" %>
              <small id="email-help" class="form-text text-muted">Seu e-mail será usado para recuperação de senha.</small>
            </div>
          </div>
        </div>

        <div class="col-3">
          <div class="form-group">
            <div class="select-field">
              <%= f.label :cargo, "Cargo" %><br />

              <% if current_user %>
                <%= f.select :cargo, gera_cargos(current_user) %>
              <% else %>
                <%= f.select :cargo, %w(Admin Secretaria Professor) %>
              <% end %>
            </div>
          </div>
        </div>

      </div>

      <div class="form-group">
        <div class="field">
          <%= f.label :password, "Senha" %><br />
          <%= f.password_field :password, autocomplete: "new-password", :class => "form-control" %>
          <small id="password-help" class="form-text text-muted">
            <% if @minimum_password_length %>
              Mínimo de <%= @minimum_password_length %> caracteres.
            <% end %>
          </small>
        </div>
      </div>

      <div class="form-group">
        <div class="field">
          <%= f.label :password_confirmation, "Confirme sua senha" %><br />
          <%= f.password_field :password_confirmation, autocomplete: "new-password", :class => "form-control" %>
        </div>
      </div>

      <div class="actions text-center">
        <%= f.submit "Sign up", :class => "btn btn-lg btn-outline-primary" %>
      </div>
    <% end %>
  </div>

</div>

app/views/home/index.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="col-10">
      <h1>Home</h1>
      <p>
        textotextotextotextotextotextotextotexto<br>
        textotextotextotextotextotextotextotexto<br>
        textotextotextotextotextotextotextotexto<br>
      </p>
    </div>
    <div class="col-2">
      <%= image_tag "cafe-sapo.jpeg", :class => "img-thumbnail rounded"%>
    </div>
  </div>
</div>

<% unless current_user %>
  <div class="lead text-center">
    <%= link_to 'Login', new_user_session_path %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Frequencia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if current_user %>
        <nav class="navbar sticky-top navbar-dark bg-dark">
          <a class="navbar-brand" href="/">Abc</a>
          <span class="navbar-text">Olá, <%= current_user.nome %> | <%= current_user.cargo %></span>

          <div class="btn-group">
            <%= link_to 'Editar e-mail', edit_cadastro_path(current_user.id), class: 'btn btn-outline-light border-0 rounded-0' %>
            <% if current_user.admin? %>
              <%= link_to 'Manejar Usuários', cadastros_path, class: 'btn btn-outline-light border-0 rounded-0' %>
            <% elsif current_user.secretaria? %>
              <%= link_to 'Manejar Professores', cadastros_path, class: 'btn btn-outline-light border-0 rounded-0' %>
              <%= link_to 'Manejar Turmas', turmas_path, class: 'btn btn-outline-light border-0 rounded-0' %>
            <% end %>
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-outline-light border-0 rounded-0' %>
          </div>
        </nav>
      <% end %>
      <%= flash_messages %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/turmas/edit.html.erb
<div class="container">
  <h2 class="text-center pb-2 mt-4 mb-2 border-bottom">Editar Turma</h2>

  <% if @turma.errors.any? %>
    <div id="error_explanation">
      <h5>
        <%= pluralize(@turma.errors.count, "erro") %> impediram esta turma de ser salva:
      </h5>
      <ul>
        <% @turma.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with model: @turma do |f| %>
    <div class="container">


      <div class="form-group">
        <div class="field">
          <%= f.label :nome, "Nome" %><br>
          <%= f.text_field :nome, autofocus: true, class: "form-control", id: "inputNome" %>
        </div>
      </div>

      <div class="row">
        <div class="col-6">
          <div class="form-group">
            <div class="field">
              <%= f.label :inicio, "Horário Início" %><br>
              <%= f.text_field :inicio, class: "form-control" %>
            </div>
          </div>
        </div>
        <div class="col-6">
          <div class="form-group">
            <div class="field">
              <%= f.label :fim, "Horário Fim" %><br>
              <%= f.text_field :fim, class: "form-control" %>
            </div>
          </div>
        </div>
      </div>


      <div class="row">
        <div class="col-6">
          <div class="form-group">
            <%= f.label :cargamin, "Carga Horária Mínima" %><br>
            <%= f.text_field :cargamin, class: "form-control" %>
          </div>
        </div>
        <div class="col-6">
          <div class="form-group">
            <%= f.label :cargamin, "Carga Horária Máxima" %><br>
            <%= f.text_field :cargamax, class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-6">
          <div class="form-group">
            <%= f.label :nome, "Capacidade" %><br>
            <%= f.text_field :capacidade, class: "form-control" %>
          </div>
        </div>
        <div class="col-6">
          <div class="form-group">
            <%= f.label :dias, "Dias da Semana" %><br>
            <%= f.select :dias, Turma::dias.keys.to_a %>
          </div>
        </div>
      </div>

      <div class="row">
        <%= f.label :user_id, "Professor" %><br>
        <%= f.select :user_id, prof_disponiveis(@turma) %>
      </div>

      <div class="text-center">
        <%= f.submit 'Salvar Turma', class: "btn btn-lg btn-outline-primary" %>
      </div>

    </div>
  <% end %>
</div>

app/views/turmas/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-5">Turmas</h1>
    <p class="lead">Criação, edição e remoção de turmas.</p>
  </div>
</div>

<div class="container">

  <table class="table table-bordered table-hover table-responsive-sm">
    <thead class="thead-dark">
    <tr>
      <th scope="col">Turma ID</th>
      <th scope="col">Nome</th>
      <th scope="col">Dia da Semana</th>
      <th scope="col">Início</th>
      <th scope="col">Fim</th>
      <th scope="col">Carga Mínima</th>
      <th scope="col">Carga Máxima</th>
      <th scope="col">Capacidade</th>
      <th scope="col">Inscritos</th>
      <th colspan="3" scope="colgroup">Controles</th>
    </tr>
    </thead>
    <tbody>
    <% @turmas.each do |turma| %>
      <tr>
        <th scope="row"><%= turma.id %></th>
        <td><%= turma.nome %></td>
        <td><%= turma.dias %></td>
        <td><%= turma.inicio.strftime('%H:%M') %></td>
        <td><%= turma.fim.strftime('%H:%M') %></td>
        <td><%= turma.cargamin %>hrs</td>
        <td><%= turma.cargamax %>hrs</td>
        <td><%= turma.capacidade %></td>
        <td><%= turma.alunos.count %></td>
        <td class="text-center"><%= link_to 'Exibir', turma_path(turma), class: "btn btn-primary btn-sm" %></td>
        <td class="text-center"><%= link_to 'Editar', edit_turma_path(turma), class: "btn btn-secondary btn-sm" %></td>
        <td class="text-center"><%= link_to 'Remover', turma_path(turma), method: :delete, data: { confirm: "Tem certeza?" }, class: "btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <%= link_to 'Nova Turma', new_turma_path, class: "btn btn-outline-primary btn-lg" %>
</div>

app/views/turmas/new.html.erb
<div class="container">
  <h2 class="text-center pb-2 mt-4 mb-2 border-bottom">Nova Turma</h2>

  <%= form_with model: @turma do |f| %>
    <div class="container">


      <div class="form-group">
        <div class="field">
          <%= f.label :nome, "Nome", class:"sr-only" %><br>
          <%= f.text_field :nome, autofocus: true, class: "form-control", id: "inputNome" %>
        </div>
      </div>

      <div class="row">
        <div class="col-6">
          <div class="form-group">
            <div class="field">
              <%= f.label :inicio, "Horário Início" %><br>
              <%= f.text_field :inicio, class: "form-control" %>
            </div>
          </div>
        </div>
        <div class="col-6">
          <div class="form-group">
            <div class="field">
              <%= f.label :fim, "Horário Fim" %><br>
              <%= f.text_field :fim, class: "form-control" %>
            </div>
          </div>
        </div>
      </div>


      <div class="row">
        <div class="col-6">
          <div class="form-group">
            <%= f.label :cargamin, "Carga Horária Mínima" %><br>
            <%= f.text_field :cargamin, class: "form-control" %>
          </div>
        </div>
        <div class="col-6">
          <div class="form-group">
            <%= f.label :cargamin, "Carga Horária Máxima" %><br>
            <%= f.text_field :cargamax, class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-6">
          <div class="form-group">
            <%= f.label :nome, "Capacidade" %><br>
            <%= f.text_field :capacidade, class: "form-control" %>
          </div>
        </div>
        <div class="col-6">
          <div class="form-group">
            <%= f.label :dias, "Dias da Semana" %><br>
            <%= f.select :dias, Turma::dias.keys.to_a %>
          </div>
        </div>
      </div>

      <div class="text-center">
        <%= f.submit 'Salvar Turma', class: "btn btn-lg btn-outline-primary" %>
      </div>

    </div>
  <% end %>

</div>

app/views/turmas/show.html.erb
<div class="container">
  <h2 class="text-center pb-2 mt-4 mb-2 border-bottom">Turma <%= @turma.nome %></h2>

  <div class="w-75 container">

    <ul class="list-group shadow pb-2">
      <li class="list-group-item lead text-center"><%= @turma.nome %></li>
      <li class="list-group-item text-center">
        <div class="row">
          <div class="col">
            Início: <%= @turma.inicio.strftime('%H:%M') %>
          </div>
          <div class="col">
            Fim: <%= @turma.fim.strftime('%H:%M') %>
          </div>
        </div>
      </li>
      <li class="list-group-item text-center">
        <div class="row">
          <div class="col">
            Carga Horária Mínima: <%= @turma.cargamin %>hrs
          </div>
          <div class="col">
            Carga Horária Máxima: <%= @turma.cargamax %>hrs
          </div>
        </div>
      </li>
      <li class="list-group-item text-center">Dia da semana: <%= @turma.dias %></li>
      <li class="list-group-item text-center">Capacidade: <%= @turma.capacidade %> alunos<span class="text-muted"> (<%= vagas_restando(@turma) %> restando)</span></li>
      <li class="list-group-item text-center"><% if @turma.user_id.nil? %>Professor: [Não Alocado]<% else %>Professor: <%=User.find(@turma.user_id).nome%><% end %></li>
      <li class="list-group-item text-center"><%= link_to 'Editar', edit_turma_path(@turma), class: "btn btn-primary" %></li>
    </ul>


    <% if @turma.alunos.count != 0 %>
      <div class="containter pb-2">
        <h5 class="pb-2 mt-4 mb-2 border-bottom">Alunos</h5>

        <table class="table table-bordered table-hover table-responsive-sm">
          <thead class="thead-dark">
          <tr>
            <th scope="col">Aluno ID</th>
            <th scope="col">Nome</th>
            <th scope="col">Matrícula</th>
            <th scope="col">Email</th>
            <th colspan="2" scope="colgroup">Controles</th>
          </tr>
          </thead>
          <tbody>
          <% @turma.alunos.each do |aluno| %>
            <tr>
              <th scope="row"><%= aluno.id %></th>
              <td><%= aluno.nome %></td>
              <td><%= aluno.matricula %></td>
              <td><%= aluno.email %></td>
              <td class="text-center"><%= link_to 'Editar', edit_turma_aluno_path(@turma, aluno), class: "btn btn-secondary btn-sm" %></td>
              <td class="text-center"><%= link_to 'Remover', [aluno.turma, aluno], method: :delete, data: { confirm: "Tem certeza?" }, class: "btn btn-danger btn-sm" %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    <% end %>

    <% if @turma.alunos.count < @turma.capacidade %>
      <h5 class="pb-2 mt-4 mb-2 border-bottom">Adicionar um aluno</h5>
      <%= form_with model: [@turma, @turma.alunos.build], local: true do |f| %>
        <div class="form-group">
          <div class="field">
            <%= f.label :nome, "Nome" %><br />
            <%= f.text_field :nome, autofocus:true, autocomplete: "nome", :class => "form-control" %>
          </div>
        </div>

        <div class="row">

          <div class="col-6">
            <div class="form-group">
              <div class="field">
                <%= f.label :matricula, "Matrícula" %><br />
                <%= f.text_field :matricula, autocomplete: "matricula", :class => "form-control" %>
              </div>
            </div>
          </div>

          <div class="col-6">
            <div class="form-group">
              <div class="field">
                <%= f.label :email, "E-mail" %><br />
                <%= f.email_field :email, autocomplete: "email", :class => "form-control" %>
              </div>
            </div>
          </div>
        </div>

        <div class="actions text-center">
          <%= f.submit "Cadastrar Aluno", :class => "btn btn-lg btn-outline-primary" %>
        </div>
      <% end %>
    <% end %>
  </div>


  <%= link_to 'Voltar', turmas_path %>
</div>